// Copy a verified browser build into the native desk, with an exact route manifest.
import { readFile, writeFile, lstat, readdir, mkdir, mkdtemp, rm } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { publishDirectory } from './publish.mjs';
const script = fileURLToPath(import.meta.url);
const root = path.dirname(script);
if (process.argv[2] !== '--locked') {
  const child = spawnSync('flock', ['-n', '-E', '75', path.join(root, '.build.lock'), process.execPath, script, '--locked'], {stdio: 'inherit'});
  if (child.error) throw child.error;
  process.exit(child.status ?? 1);
}
const repository = path.resolve(root, '../..');
const remote = spawnSync('git', ['remote', 'get-url', '--push', 'origin'], {cwd: repository, encoding: 'utf8'});
if (remote.status !== 0 || remote.stdout.trim() !== 'https://github.com/ScottTpirate/stead-urbit.git') throw new Error('Derivative origin required');
const dist = path.join(root, 'dist');
const manifestBytes = await readFile(path.join(dist, 'manifest.json'));
const manifest = JSON.parse(manifestBytes.toString('utf8'));
if (manifest.format !== 1 || manifest.classification !== 'frontend-build-only' || !manifest.files?.['index.html']) throw new Error('Unsupported build manifest');
const names = Object.keys(manifest.files).sort();
if (names.length > 32 || JSON.stringify((await readdir(dist)).sort()) !== JSON.stringify([...names, 'manifest.json', 'metafile.json'].sort())) throw new Error('Unexpected build output inventory');
const rows = []; const files = new Map();
for (const name of names) {
  if (!/^[A-Za-z0-9][A-Za-z0-9.-]{0,127}$/u.test(name) || name.includes('..')) throw new Error('Unsafe asset name');
  const source = path.join(dist, name); const stat = await lstat(source);
  if (!stat.isFile() || stat.size > 524288) throw new Error('Asset is not a bounded regular file');
  const bytes = await readFile(source); const hash = createHash('sha256').update(bytes).digest('hex');
  if (bytes.length !== manifest.files[name].bytes || hash !== manifest.files[name].sha256) throw new Error('Build manifest mismatch');
  const dot = name.lastIndexOf('.'); const stem = name.slice(0, dot); const extension = name.slice(dot + 1);
  const mime = {js: 'text/javascript; charset=utf-8', css: 'text/css; charset=utf-8', html: 'text/html; charset=utf-8', txt: 'text/plain; charset=utf-8'}[extension];
  if (!mime) throw new Error('Unsupported asset type');
  const route = name === 'index.html' ? '/stead/' : name === 'identity.html' ? '/stead-identity/' : (name.startsWith('identity.') ? '/stead-identity/assets/' : '/stead/assets/') + name;
  // A dedicated raw mark avoids %txt's line-list conversion and preserves
  // exact bytes regardless of display filename or extension.
  const stored = 'asset-' + hash;
  rows.push(`      ['${route}' [[%web %stead '${stored}' %stead-asset ~] '${mime}' '${hash}']]`);
  // Split entry points may share generated chunks. Each app resolves relative
  // imports inside its own fixed prefix, with the same verified bytes.
  if (name.startsWith('chunk-') || name === 'NOTICE.txt') {
    rows.push(`      ['/stead-identity/assets/${name}' [[%web %stead '${stored}' %stead-asset ~] '${mime}' '${hash}']]`);
  }
  files.set(stored + '.stead-asset', bytes);
}
if (rows.length > 32) throw new Error('Native route inventory bound');
const source = `::  Generated by web/app/package-desk.mjs from verified manifest bytes.\n|%\n+$  asset  [file=path mime=@t digest=@t]\n++  inventory\n  ^-  (map @t asset)\n  %-  malt\n  :~\n${rows.join('\n')}\n  ==\n++  paths\n  ^-  (set @t)\n  (silt (turn ~(tap by inventory) |=([route=@t value=asset] route)))\n--\n`;
const desk = path.join(repository, 'native/core/desk'); const parent = path.join(desk, 'web');
await mkdir(parent, {recursive: true});
const staging = await mkdtemp(path.join(parent, '.stead-assets-'));
try {
  for (const [name, bytes] of files) await writeFile(path.join(staging, name), bytes);
  await writeFile(path.join(staging, 'inventory.hoon'), source);
  await publishDirectory(staging, path.join(parent, 'stead'));
} finally { await rm(staging, {recursive: true, force: true}); }
console.log(JSON.stringify({classification: 'packaged-assets-only', files: names.length, manifest_sha256: createHash('sha256').update(manifestBytes).digest('hex')}, null, 2));
