#!/usr/bin/env python3
"""Bind this test's Hoon constants to frozen public fixture/corpus bytes.

Generation/checking is host metadata work, never native acceptance evidence.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SPEC = importlib.util.spec_from_file_location(
    "schedule_contracts_v2", ROOT / "scripts/urbit/contracts_v2.py")
C = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(C)


def expected():
    C.verify_freeze()
    fixture_path = "specs/urbit/native-fixture.json"
    corpus_path = "specs/urbit/fixtures/native-cases-v2.json"
    fixture = (ROOT / fixture_path).read_bytes()
    corpus = json.loads((ROOT / corpus_path).read_bytes())
    chosen = {
        "fixture": fixture,
        "project": C.canonical(corpus["commands"]["project_create"]),
        "grant": C.canonical(corpus["commands"]["grant_bus_contributor"]),
        "work": C.canonical(corpus["commands"]["work_a_create"]),
    }
    for name in ("project", "grant", "work"):
        C.parse(chosen[name])
    lines = ["::  Generated by tests/urbit/native_gall_schedule/build_inputs.py.",
             "::  Public corpus constants only; no executed-test claim.", "|%"]
    for name, raw in chosen.items():
        if not raw or raw.endswith(b"\0") or len(raw) > 65536:
            raise ValueError("Input cord bounds")
        lines.extend([f"++  {name}", f"  `@t`0x{int.from_bytes(raw, 'little'):x}"])
    lines.extend(["--", ""])
    source = "\n".join(lines).encode()
    manifest = {
        "classification": "generated-input-metadata-not-native-evidence",
        "kernel_commit": "5a187fededc4582a34fcd6055c67bb63e0917b94",
        "fixed_clock": "2026-09-25T00:00:00Z",
        "source_files": {
            path: hashlib.sha256((ROOT / path).read_bytes()).hexdigest()
            for path in (fixture_path, corpus_path,
                         "specs/urbit/v2/contract-freeze.json")
        },
        "constants": {
            name: {"bytes": len(raw), "sha256": hashlib.sha256(raw).hexdigest()}
            for name, raw in chosen.items()
        },
        "commands": {name: corpus["commands"][key] for name, key in (
            ("project", "project_create"), ("grant", "grant_bus_contributor"),
            ("work", "work_a_create"))},
        "generated_hoon_sha256": hashlib.sha256(source).hexdigest(),
    }
    return source, (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    source, manifest = expected()
    outputs = {HERE / "desk/lib/stead-gall-schedule-inputs.hoon": source,
               HERE / "inputs.json": manifest}
    if args.write:
        remote = subprocess.check_output(
            ["git", "remote", "get-url", "--push", "origin"], cwd=ROOT, text=True).strip()
        if remote != "https://github.com/ScottTpirate/stead-urbit.git":
            raise SystemExit("Refusing write outside the authorized derivative remote")
        for path, raw in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(raw)
    elif any(not path.is_file() or path.read_bytes() != raw for path, raw in outputs.items()):
        raise SystemExit("Generated schedule input drift")
    print("PASS generated input metadata only; native schedule remains unexecuted")


if __name__ == "__main__":
    main()
