::  Generated by web/app/package-desk.mjs from verified manifest bytes.
|%
+$  asset  [file=path mime=@t digest=@t]
++  inventory
  ^-  (map @t asset)
  %-  malt
  :~
      ['/stead/assets/NOTICE.txt' [[%web %stead 'asset-1f7ace5da42d050917f462ec832cca5f88550cafed6f4bbfe680886a033efdab' %stead-asset ~] 'text/plain; charset=utf-8' '1f7ace5da42d050917f462ec832cca5f88550cafed6f4bbfe680886a033efdab']]
      ['/stead-identity/assets/NOTICE.txt' [[%web %stead 'asset-1f7ace5da42d050917f462ec832cca5f88550cafed6f4bbfe680886a033efdab' %stead-asset ~] 'text/plain; charset=utf-8' '1f7ace5da42d050917f462ec832cca5f88550cafed6f4bbfe680886a033efdab']]
      ['/stead/assets/app.css' [[%web %stead 'asset-1a9f5d9457946d789eb168c56e2c713d8ac6cfba8a49f8989f22713c391b08fc' %stead-asset ~] 'text/css; charset=utf-8' '1a9f5d9457946d789eb168c56e2c713d8ac6cfba8a49f8989f22713c391b08fc']]
      ['/stead/assets/app.js' [[%web %stead 'asset-ad3899bd30247494abff980049406defd46d61adbaf40db74c0dd2d70e590616' %stead-asset ~] 'text/javascript; charset=utf-8' 'ad3899bd30247494abff980049406defd46d61adbaf40db74c0dd2d70e590616']]
      ['/stead/assets/app.js.LEGAL.txt' [[%web %stead 'asset-b0f578720c3cda257868108d7295bb78a4535609648dccc4116da960f61520a8' %stead-asset ~] 'text/plain; charset=utf-8' 'b0f578720c3cda257868108d7295bb78a4535609648dccc4116da960f61520a8']]
      ['/stead/assets/chunk-6Y6IVGOI.js' [[%web %stead 'asset-0f0d3399c251aec81df779c788121ece1e2f3f79130fe92709645e8e8cd4ccff' %stead-asset ~] 'text/javascript; charset=utf-8' '0f0d3399c251aec81df779c788121ece1e2f3f79130fe92709645e8e8cd4ccff']]
      ['/stead-identity/assets/chunk-6Y6IVGOI.js' [[%web %stead 'asset-0f0d3399c251aec81df779c788121ece1e2f3f79130fe92709645e8e8cd4ccff' %stead-asset ~] 'text/javascript; charset=utf-8' '0f0d3399c251aec81df779c788121ece1e2f3f79130fe92709645e8e8cd4ccff']]
      ['/stead/assets/chunk-E5WJYM75.js' [[%web %stead 'asset-0e31fab7cf6c399f805dc874f264885c9238ce6fb0635c3b3f0089deaf679f7f' %stead-asset ~] 'text/javascript; charset=utf-8' '0e31fab7cf6c399f805dc874f264885c9238ce6fb0635c3b3f0089deaf679f7f']]
      ['/stead-identity/assets/chunk-E5WJYM75.js' [[%web %stead 'asset-0e31fab7cf6c399f805dc874f264885c9238ce6fb0635c3b3f0089deaf679f7f' %stead-asset ~] 'text/javascript; charset=utf-8' '0e31fab7cf6c399f805dc874f264885c9238ce6fb0635c3b3f0089deaf679f7f']]
      ['/stead/assets/chunk-E5WJYM75.js.LEGAL.txt' [[%web %stead 'asset-bc5112824c7d9bce98cf1667c0d7e5db217c1ccce14a21ef3b9c0a06f2bc40d5' %stead-asset ~] 'text/plain; charset=utf-8' 'bc5112824c7d9bce98cf1667c0d7e5db217c1ccce14a21ef3b9c0a06f2bc40d5']]
      ['/stead-identity/assets/chunk-E5WJYM75.js.LEGAL.txt' [[%web %stead 'asset-bc5112824c7d9bce98cf1667c0d7e5db217c1ccce14a21ef3b9c0a06f2bc40d5' %stead-asset ~] 'text/plain; charset=utf-8' 'bc5112824c7d9bce98cf1667c0d7e5db217c1ccce14a21ef3b9c0a06f2bc40d5']]
      ['/stead/assets/chunk-SQE76S5B.js' [[%web %stead 'asset-11247d28c5c2fb3d976002c2b55fecb6ba19fd88153e11d2c7af5832fd6ff331' %stead-asset ~] 'text/javascript; charset=utf-8' '11247d28c5c2fb3d976002c2b55fecb6ba19fd88153e11d2c7af5832fd6ff331']]
      ['/stead-identity/assets/chunk-SQE76S5B.js' [[%web %stead 'asset-11247d28c5c2fb3d976002c2b55fecb6ba19fd88153e11d2c7af5832fd6ff331' %stead-asset ~] 'text/javascript; charset=utf-8' '11247d28c5c2fb3d976002c2b55fecb6ba19fd88153e11d2c7af5832fd6ff331']]
      ['/stead-identity/assets/identity.css' [[%web %stead 'asset-6016a28499433ab016b68e48afe0515cacc0032d24bb1b1da1dca0563a466be0' %stead-asset ~] 'text/css; charset=utf-8' '6016a28499433ab016b68e48afe0515cacc0032d24bb1b1da1dca0563a466be0']]
      ['/stead-identity/' [[%web %stead 'asset-08a1794a61e7ed673d2e66de355cda8680a87a9dff4de7245ac987909ce7b1ed' %stead-asset ~] 'text/html; charset=utf-8' '08a1794a61e7ed673d2e66de355cda8680a87a9dff4de7245ac987909ce7b1ed']]
      ['/stead-identity/assets/identity.js' [[%web %stead 'asset-2620951f45589c393f7a9dd8ddd24a5cbe82a8ce84699216da05eb7fc9c9ffe6' %stead-asset ~] 'text/javascript; charset=utf-8' '2620951f45589c393f7a9dd8ddd24a5cbe82a8ce84699216da05eb7fc9c9ffe6']]
      ['/stead/' [[%web %stead 'asset-4ad0a8c304f247405c5314f49b27fac259aa8f52458868bfe6e5f79760ad7a95' %stead-asset ~] 'text/html; charset=utf-8' '4ad0a8c304f247405c5314f49b27fac259aa8f52458868bfe6e5f79760ad7a95']]
  ==
++  paths
  ^-  (set @t)
  (silt (turn ~(tap by inventory) |=([route=@t value=asset] route)))
--
